name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Build nfd.dll
      working-directory: ${{github.workspace}}
      run: msbuild 'NativeFileDialog.NET\dynamicLib\VS2019\nfd_dll.sln' -p:Configuration='Debug' -p:Platform='x64'
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build CBRE.Editor -p:Platform="x64" -c Debug
    - uses: actions/upload-artifact@v2
      with:
        name: CBRE.Editor Build
        path: CBRE.Editor/bin/Debug/net6.0/
        retention-days: 5
